### ISSUE TITLE
CPPickerview in scrollview resets itself

### ISSUE THREAD

**Issue by rmcnamara** [cbpowell/CPPickerView#1]
Add the control to a table view that scrolls, change the value, scroll it offscreen, and scroll it back onto the screen-- the view will be back to the item at index 0.

**Comment by rmcnamara** [comment]
Actually, this was my fault, failure to manage the uitableview properly-- sorry to waste issue #1 ;)

**Comment by cbpowell** [comment]
No worries - yeah unfortunately even to do a quick test you've got to store and restore the settings, since you don't really know what cell you're getting back from the dequeue method.
