### ISSUE TITLE
malloc: *** error for object 0x#######: double free

### ISSUE THREAD

**Issue by kayzee** [cbpowell/CPPickerView#2]
I'm trying to use the CPPickerView inside of a typical UITableView cell.

Inside the tableView data source, I have some code to create the cell:

```
-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath,
{
    cell = [tableView dequeueReusableCellWithIdentifier:@"PickerCell"];

    UILabel *lblName = (UILabel *)[cell viewWithTag:100];
    lblName.text = [NSString stringWithString@"Name"];

    CPPickerView *picker = [[CPPickerView alloc] initWithFrame:CGRectMake(197, 8, 112, 30)];
    picker.itemFont = [UIFont boldSystemFontOfSize:14];
    picker.dataSource = self;
    picker.delegate = self;
    [picker reloadData];
    [cell addSubview:picker];
    return cell;
}
```

When I run this code and it populates my table, I get the following error multiple times:

MyApp72404,0xac51f2c0) malloc: **\* error for object 0xb51ad30: double free
**\* set a breakpoint in malloc_error_break to debug
MyApp(72404,0xac51f2c0) malloc: **\* error for object 0xb51ad30: double free
**\* set a breakpoint in malloc_error_break to debug
MyApp(72404,0xac51f2c0) malloc: **\* error for object 0xb51ad30: double free
**\* set a breakpoint in malloc_error_break to debug
MyApp(72404,0xac51f2c0) malloc: **\* error for object 0xb51ad30: double free
**\* set a breakpoint in malloc_error_break to debug

I found out that if I comment out the following line, it works fine:
//picker.itemFont = [UIFont boldSystemFontOfSize:14];

I should note that I have disabled ARC for the CPPickerView class.

**Comment by kayzee** [comment]
This is still an odd issue, but I did figure out how to use your property and change the font dynamically (as opposed to setting it in the -(void)setup method, which was my initial workaround).

Causes the bug above:
    picker.itemFont = [UIFont boldSystemFontOfSize:17];

Works fine:
    [picker setItemFont:[UIFont boldSystemFontOfSize:17]];

**Comment by cbpowell** [comment]
Aha - discovered a possible cause. I'd missed renaming the custom mutator for the picker.itemFont property from the code I adapted CPPickerView from. It was still named `setRowFont:`, but I'd changed the property to itemFont. I suspect that was the problem given how you fixed it, try out the latest commit (which also includes your other suggested fix).

**Comment by kayzee** [comment]
Tested the lasted commit..works as expected with picker.itemFont = ...
