### ISSUE TITLE
ScrollsToTop doesn't work in App

### ISSUE THREAD

**Issue by kayzee** [cbpowell/CPPickerView#3]
I had issues getting "scrollsToTop" to work properly in my app.  What I found out is that only ONE view can have the "scrollsToTop" property set to true at any time for the app to scroll to the top when tapping the status bar.

To fix in your control, I added one line of code to the  - (id)initWithFrame:(CGRect)frame method in CPPickerView.m

// content
...
self.contentView.scrollsToTop = NO;
...

Not sure if you needed this property in for another reason, but I believe the default value is YES, so setting it to no does the trick.

**Comment by cbpowell** [comment]
Good catch, added this in - thanks!
