### ISSUE TITLE
RGBACOLOR warning

### ISSUE THREAD

**Issue by kayzee** [cbpowell/CPPickerView#4]
I forgot about this one when I submitted the other two issues.

In -(void)tileViews:

```
label.textColor = RGBACOLOR(0.0, 0.0, 0.0, 0.75);
```

gives a warning: "Implicit declaration of function 'RGBACOLOR' is invalid in C99"

Of course this is just a warning and I'm not sure why my Target is set to use GNUC99 now, but regardless, I changed this line to 

```
label.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.75];
```

which matches of [UIColor ] calls you made elsewhere.

**Comment by cbpowell** [comment]
That's some more leftover code I hadn't noticed. Fixed it in the latest commit, and added an itemColor property since that's probably a desirable customization anyway.
