### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by ghass64** [cbpowell/CPPickerView#6]
when i used your cPPickerView in my table its shows black but when highlighte it it appears , when the highighted goes away ,, its return black ,, do u have any idea how to fix that !??

**Comment by cbpowell** [comment]
Could you post some of the code you're using to configure and add the CPPickerView or CPPickerViewCell to your table rows? Cell row highlighting works fine in the demo provided with the project (the standard blue highlighting shows behind the picker), so something must be different. Alternatively, could you be adding any views above the picker view?

**Comment by ghass64** [comment]
i just figure out the problem ,, i wasn't include the background image in my project ,, now its fine and working well 
thanks

**Comment by cbpowell** [comment]
Ah, great!
